### ISSUE TITLE
Weird interpolations

### ISSUE THREAD

**Issue by pjlsergeant** [graphql-perl/graphql-perl#3]
Consider:

```perl
#!perl

use strict;
use warnings;

use GraphQL::Schema;
use GraphQL::Execution 'execute';
use DateTime;

my $schema = GraphQL::Schema->from_doc(<<'EOF');
schema { query: Query }
type DateTime { ymd: String }
type Query { dateTimeNow: DateTime }
EOF

my $root_value = { dateTimeNow => sub { DateTime->now } };

my @z = execute(
    $schema,
    "{ dateTimeNow { ymd } }",
    $root_value
);

use Data::Printer;
p @z;
```

Expected:

```perl
[
    [0] {
        data   {
            dateTimeNow   {
                ymd   "2017-10-25"
            }
        }
    }
]
```

Actual:

```perl
[
    [0] {
        data   {
            dateTimeNow   {
                ymd   "2017HASH(0x7feca88e87b8)10HASH(0x7feca88e87b8)25"
            }
        }
    }
]
```

**Comment by mohawk2** [comment]
The problem here is in how resolvers are called, and what they return. Your top-level `$root_value` has the top-level `dateTimeNow` return a `DateTime` object, as created with the class method `now`.

Your schema allows for the subfield of that, `ymd`, to be looked for within that value. The default field resolver, which currently lives at https://github.com/graphql-perl/graphql-perl/blob/master/lib/GraphQL/Execution.pm#L775-L800, will use `can` on the "root value" (here the `DateTime` object) to see if it can execute a `ymd`. It can! Therefore it will do so, passing the standard arguments of `$args, $context, $info`.

`ymd` takes one arg, a string to use as the separator. Here that will be a hash-ref, so you then get what you see above - year, month, date separate by `HASH(0x7feca88e87b8)`, which is exactly what you asked for though not what you want.

To get what you want, you would need to override the default field resolver, like this (modified from the new https://github.com/graphql-perl/graphql-perl/blob/master/t/perl.t):

```
use strict;
use warnings;

use GraphQL::Schema;
use GraphQL::Execution 'execute';
use DateTime;

my $schema = GraphQL::Schema->from_doc(<<'EOF');
schema { query: Query }
type DateTime { ymd: String }
type Query { dateTimeNow: DateTime }
EOF

my $root_value = { dateTimeNow => sub { DateTime->now } };

my @z = execute(
    $schema,
    "{ dateTimeNow { ymd } }",
    $root_value,
    (undef) x 3,
    sub {
      my ($root_value, $args, $context, $info) = @_;
      my $field_name = $info->{field_name};
      my $property = ref($root_value) eq 'HASH'
        ? $root_value->{$field_name}
        : $root_value;
      return $property->($args, $context, $info) if ref $property eq 'CODE';
      return $root_value->$field_name if ref $property; # no args
      $property;
    },
);

use Data::Printer;
p @z;
```

**Comment by mohawk2** [comment]
Closed as agreed.
